import type { WaveformChannel } from '@terra-pulse/schema';
import raw from '../data/waveform-regions.json';

/**
 * The region presets, generated by `scripts/vendor-waveform-stations.mjs` from
 * the ring's own stream list crossed with the FDSN station service.
 *
 * **A region is nothing more than a way of producing a `WaveformChannel[]`.**
 * `waveforms:start` takes channels, never a preset id; main never learns that
 * regions exist. That is what keeps the planned globe-click station picker
 * additive: a click produces a channel and calls the same `start`, with no
 * change to main, the buffer or the rendering.
 */

/** A preset station: a channel plus what the UI needs to label it. */
export interface WaveformRegionChannel extends WaveformChannel {
  latitude: number;
  longitude: number;
  site: string;
  /** From station metadata. The record's own rate is what actually gets used. */
  sampleRateHz: number;
}

export interface WaveformRegion {
  id: string;
  label: string;
  network: string;
  channel: string;
  note: string;
  channels: WaveformRegionChannel[];
}

interface RegionFile {
  generatedUtc: string;
  ring: string;
  stationService: string;
  regions: WaveformRegion[];
}

// Typed once here so nothing else imports the JSON directly — the same
// arrangement `fault-data.ts` uses, and the reason is the same: one place to
// state the shape, and one place to change if the vendor script's output moves.
// An annotation rather than an assertion, so a vendor script that stopped
// emitting a field would fail here instead of being asserted over.
const file: RegionFile = raw;

export const WAVEFORM_REGIONS: readonly WaveformRegion[] = file.regions;

/** When these presets were last checked against the live ring. */
export const WAVEFORM_REGIONS_GENERATED_UTC: string = file.generatedUtc;

export const DEFAULT_WAVEFORM_REGION_ID: string = WAVEFORM_REGIONS[0]?.id ?? '';

export function waveformRegionById(id: string): WaveformRegion | undefined {
  return WAVEFORM_REGIONS.find((region) => region.id === id);
}

/**
 * The bare channels to stream, with the display fields stripped.
 *
 * Not cosmetic: `waveforms:start` is validated in main against an exact shape,
 * and sending coordinates and site names through it would widen what crosses
 * the bridge for no reason.
 */
export function channelsOf(region: WaveformRegion): WaveformChannel[] {
  return region.channels.map(({ network, station, location, channel }) => ({
    network,
    station,
    location,
    channel,
  }));
}
